// ==================================================
// MPGB PREMIER LEAGUE – TEAM SQUADS (ALL 22 TEAMS)
// UNIQUE PLAYER NAMES | SAFE FILE
// ==================================================

const TEAM_SQUADS = {

"Bhopal":[
{id:"BH1",name:"Amit Rahul Kumar",role:"Batsman",speciality:"Opener"},
{id:"BH2",name:"Rohit Aakash Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"BH3",name:"Sandeep Manoj Kumar",role:"Bowler",speciality:"Fast"},
{id:"BH4",name:"Vikas Deepak Kumar",role:"Batsman",speciality:"Anchor"},
{id:"BH5",name:"Nitin Kunal Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"BH6",name:"Rahul Pankaj Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"BH7",name:"Aakash Sachin Kumar",role:"Bowler",speciality:"Swing"},
{id:"BH8",name:"Manoj Harshit Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"BH9",name:"Deepak Ankit Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"BH10",name:"Kunal Sunil Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"BH11",name:"Pankaj Rakesh Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"BH12",name:"Sachin Abhishek Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"BH13",name:"Harshit Nilesh Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"BH14",name:"Ankit Saurabh Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"BH15",name:"Sunil Dinesh Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Chhatarpur":[
{id:"CH1",name:"Vikas Deepak Kumar",role:"Batsman",speciality:"Opener"},
{id:"CH2",name:"Nitin Kunal Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"CH3",name:"Rahul Pankaj Kumar",role:"Bowler",speciality:"Fast"},
{id:"CH4",name:"Aakash Sachin Kumar",role:"Batsman",speciality:"Anchor"},
{id:"CH5",name:"Manoj Harshit Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"CH6",name:"Deepak Ankit Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"CH7",name:"Kunal Sunil Kumar",role:"Bowler",speciality:"Swing"},
{id:"CH8",name:"Pankaj Rakesh Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"CH9",name:"Sachin Abhishek Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"CH10",name:"Harshit Nilesh Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"CH11",name:"Ankit Saurabh Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"CH12",name:"Sunil Dinesh Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"CH13",name:"Rakesh Manish Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"CH14",name:"Abhishek Piyush Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"CH15",name:"Nilesh Alok Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Chhindwara":[
{id:"CW1",name:"Aakash Sachin Kumar",role:"Batsman",speciality:"Opener"},
{id:"CW2",name:"Manoj Harshit Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"CW3",name:"Deepak Ankit Kumar",role:"Bowler",speciality:"Fast"},
{id:"CW4",name:"Kunal Sunil Kumar",role:"Batsman",speciality:"Anchor"},
{id:"CW5",name:"Pankaj Rakesh Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"CW6",name:"Sachin Abhishek Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"CW7",name:"Harshit Nilesh Kumar",role:"Bowler",speciality:"Swing"},
{id:"CW8",name:"Ankit Saurabh Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"CW9",name:"Sunil Dinesh Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"CW10",name:"Rakesh Manish Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"CW11",name:"Abhishek Piyush Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"CW12",name:"Nilesh Alok Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"CW13",name:"Saurabh Kapil Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"CW14",name:"Dinesh Yogesh Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"CW15",name:"Manish Pradeep Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Damoh":[
{id:"DA1",name:"Kunal Sunil Kumar",role:"Batsman",speciality:"Opener"},
{id:"DA2",name:"Pankaj Rakesh Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"DA3",name:"Sachin Abhishek Kumar",role:"Bowler",speciality:"Fast"},
{id:"DA4",name:"Harshit Nilesh Kumar",role:"Batsman",speciality:"Anchor"},
{id:"DA5",name:"Ankit Saurabh Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"DA6",name:"Sunil Dinesh Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"DA7",name:"Rakesh Manish Kumar",role:"Bowler",speciality:"Swing"},
{id:"DA8",name:"Abhishek Piyush Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"DA9",name:"Nilesh Alok Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"DA10",name:"Saurabh Kapil Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"DA11",name:"Dinesh Yogesh Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"DA12",name:"Manish Pradeep Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"DA13",name:"Piyush Anuj Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"DA14",name:"Alok Aman Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"DA15",name:"Kapil Vivek Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Dewas":[
{id:"DE1",name:"Harshit Nilesh Kumar",role:"Batsman",speciality:"Opener"},
{id:"DE2",name:"Ankit Saurabh Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"DE3",name:"Sunil Dinesh Kumar",role:"Bowler",speciality:"Fast"},
{id:"DE4",name:"Rakesh Manish Kumar",role:"Batsman",speciality:"Anchor"},
{id:"DE5",name:"Abhishek Piyush Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"DE6",name:"Nilesh Alok Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"DE7",name:"Saurabh Kapil Kumar",role:"Bowler",speciality:"Swing"},
{id:"DE8",name:"Dinesh Yogesh Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"DE9",name:"Manish Pradeep Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"DE10",name:"Piyush Anuj Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"DE11",name:"Alok Aman Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"DE12",name:"Kapil Vivek Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"DE13",name:"Yogesh Shubham Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"DE14",name:"Pradeep Kartik Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"DE15",name:"Anuj Ravi Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Dhar":[
{id:"DH1",name:"Rakesh Manish Kumar",role:"Batsman",speciality:"Opener"},
{id:"DH2",name:"Abhishek Piyush Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"DH3",name:"Nilesh Alok Kumar",role:"Bowler",speciality:"Fast"},
{id:"DH4",name:"Saurabh Kapil Kumar",role:"Batsman",speciality:"Anchor"},
{id:"DH5",name:"Dinesh Yogesh Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"DH6",name:"Manish Pradeep Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"DH7",name:"Piyush Anuj Kumar",role:"Bowler",speciality:"Swing"},
{id:"DH8",name:"Alok Aman Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"DH9",name:"Kapil Vivek Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"DH10",name:"Yogesh Shubham Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"DH11",name:"Pradeep Kartik Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"DH12",name:"Anuj Ravi Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"DH13",name:"Aman Mukesh Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"DH14",name:"Vivek Anurag Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"DH15",name:"Shubham Pawan Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Gwalior":[
{id:"GW1",name:"Saurabh Kapil Kumar",role:"Batsman",speciality:"Opener"},
{id:"GW2",name:"Dinesh Yogesh Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"GW3",name:"Manish Pradeep Kumar",role:"Bowler",speciality:"Fast"},
{id:"GW4",name:"Piyush Anuj Kumar",role:"Batsman",speciality:"Anchor"},
{id:"GW5",name:"Alok Aman Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"GW6",name:"Kapil Vivek Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"GW7",name:"Yogesh Shubham Kumar",role:"Bowler",speciality:"Swing"},
{id:"GW8",name:"Pradeep Kartik Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"GW9",name:"Anuj Ravi Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"GW10",name:"Aman Mukesh Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"GW11",name:"Vivek Anurag Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"GW12",name:"Shubham Pawan Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"GW13",name:"Kartik Gaurav Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"GW14",name:"Ravi Siddharth Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"GW15",name:"Mukesh Vijay Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Head Office":[
{id:"HO1",name:"Piyush Anuj Kumar",role:"Batsman",speciality:"Opener"},
{id:"HO2",name:"Alok Aman Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"HO3",name:"Kapil Vivek Kumar",role:"Bowler",speciality:"Fast"},
{id:"HO4",name:"Yogesh Shubham Kumar",role:"Batsman",speciality:"Anchor"},
{id:"HO5",name:"Pradeep Kartik Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"HO6",name:"Anuj Ravi Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"HO7",name:"Aman Mukesh Kumar",role:"Bowler",speciality:"Swing"},
{id:"HO8",name:"Vivek Anurag Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"HO9",name:"Shubham Pawan Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"HO10",name:"Kartik Gaurav Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"HO11",name:"Ravi Siddharth Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"HO12",name:"Mukesh Vijay Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"HO13",name:"Anurag Akash Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"HO14",name:"Pawan Neeraj Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"HO15",name:"Gaurav Mohit Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Jabalpur":[
{id:"JB1",name:"Yogesh Shubham Kumar",role:"Batsman",speciality:"Opener"},
{id:"JB2",name:"Pradeep Kartik Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"JB3",name:"Anuj Ravi Kumar",role:"Bowler",speciality:"Fast"},
{id:"JB4",name:"Aman Mukesh Kumar",role:"Batsman",speciality:"Anchor"},
{id:"JB5",name:"Vivek Anurag Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"JB6",name:"Shubham Pawan Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"JB7",name:"Kartik Gaurav Kumar",role:"Bowler",speciality:"Swing"},
{id:"JB8",name:"Ravi Siddharth Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"JB9",name:"Mukesh Vijay Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"JB10",name:"Anurag Akash Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"JB11",name:"Pawan Neeraj Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"JB12",name:"Gaurav Mohit Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"JB13",name:"Siddharth Ajay Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"JB14",name:"Vijay Arjun Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"JB15",name:"Akash Santosh Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Jhabua":[
{id:"JH1",name:"Aman Mukesh Kumar",role:"Batsman",speciality:"Opener"},
{id:"JH2",name:"Vivek Anurag Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"JH3",name:"Shubham Pawan Kumar",role:"Bowler",speciality:"Fast"},
{id:"JH4",name:"Kartik Gaurav Kumar",role:"Batsman",speciality:"Anchor"},
{id:"JH5",name:"Ravi Siddharth Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"JH6",name:"Mukesh Vijay Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"JH7",name:"Anurag Akash Kumar",role:"Bowler",speciality:"Swing"},
{id:"JH8",name:"Pawan Neeraj Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"JH9",name:"Gaurav Mohit Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"JH10",name:"Siddharth Ajay Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"JH11",name:"Vijay Arjun Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"JH12",name:"Akash Santosh Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"JH13",name:"Neeraj Sanjay Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"JH14",name:"Mohit Naveen Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"JH15",name:"Ajay Dilip Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Khargone":[
{id:"KH1",name:"Kartik Gaurav Kumar",role:"Batsman",speciality:"Opener"},
{id:"KH2",name:"Ravi Siddharth Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"KH3",name:"Mukesh Vijay Kumar",role:"Bowler",speciality:"Fast"},
{id:"KH4",name:"Anurag Akash Kumar",role:"Batsman",speciality:"Anchor"},
{id:"KH5",name:"Pawan Neeraj Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"KH6",name:"Gaurav Mohit Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"KH7",name:"Siddharth Ajay Kumar",role:"Bowler",speciality:"Swing"},
{id:"KH8",name:"Vijay Arjun Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"KH9",name:"Akash Santosh Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"KH10",name:"Neeraj Sanjay Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"KH11",name:"Mohit Naveen Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"KH12",name:"Ajay Dilip Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"KH13",name:"Arjun Ashutosh Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"KH14",name:"Santosh Amit Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"KH15",name:"Sanjay Rohit Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Mandla":[
{id:"MD1",name:"Anurag Akash Kumar",role:"Batsman",speciality:"Opener"},
{id:"MD2",name:"Pawan Neeraj Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"MD3",name:"Gaurav Mohit Kumar",role:"Bowler",speciality:"Fast"},
{id:"MD4",name:"Siddharth Ajay Kumar",role:"Batsman",speciality:"Anchor"},
{id:"MD5",name:"Vijay Arjun Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"MD6",name:"Akash Santosh Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"MD7",name:"Neeraj Sanjay Kumar",role:"Bowler",speciality:"Swing"},
{id:"MD8",name:"Mohit Naveen Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"MD9",name:"Ajay Dilip Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"MD10",name:"Arjun Ashutosh Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"MD11",name:"Santosh Amit Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"MD12",name:"Sanjay Rohit Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"MD13",name:"Naveen Sandeep Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"MD14",name:"Dilip Vikas Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"MD15",name:"Ashutosh Nitin Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Mandsaur":[
{id:"MS1",name:"Siddharth Ajay Kumar",role:"Batsman",speciality:"Opener"},
{id:"MS2",name:"Vijay Arjun Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"MS3",name:"Akash Santosh Kumar",role:"Bowler",speciality:"Fast"},
{id:"MS4",name:"Neeraj Sanjay Kumar",role:"Batsman",speciality:"Anchor"},
{id:"MS5",name:"Mohit Naveen Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"MS6",name:"Ajay Dilip Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"MS7",name:"Arjun Ashutosh Kumar",role:"Bowler",speciality:"Swing"},
{id:"MS8",name:"Santosh Amit Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"MS9",name:"Sanjay Rohit Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"MS10",name:"Naveen Sandeep Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"MS11",name:"Dilip Vikas Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"MS12",name:"Ashutosh Nitin Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"MS13",name:"Amit Rahul Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"MS14",name:"Rohit Aakash Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"MS15",name:"Sandeep Manoj Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Narmadapuram":[
{id:"NP1",name:"Neeraj Sanjay Kumar",role:"Batsman",speciality:"Opener"},
{id:"NP2",name:"Mohit Naveen Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"NP3",name:"Ajay Dilip Kumar",role:"Bowler",speciality:"Fast"},
{id:"NP4",name:"Arjun Ashutosh Kumar",role:"Batsman",speciality:"Anchor"},
{id:"NP5",name:"Santosh Amit Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"NP6",name:"Sanjay Rohit Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"NP7",name:"Naveen Sandeep Kumar",role:"Bowler",speciality:"Swing"},
{id:"NP8",name:"Dilip Vikas Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"NP9",name:"Ashutosh Nitin Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"NP10",name:"Amit Rahul Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"NP11",name:"Rohit Aakash Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"NP12",name:"Sandeep Manoj Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"NP13",name:"Vikas Deepak Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"NP14",name:"Nitin Kunal Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"NP15",name:"Rahul Pankaj Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Rewa":[
{id:"RW1",name:"Arjun Ashutosh Kumar",role:"Batsman",speciality:"Opener"},
{id:"RW2",name:"Santosh Amit Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"RW3",name:"Sanjay Rohit Kumar",role:"Bowler",speciality:"Fast"},
{id:"RW4",name:"Naveen Sandeep Kumar",role:"Batsman",speciality:"Anchor"},
{id:"RW5",name:"Dilip Vikas Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"RW6",name:"Ashutosh Nitin Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"RW7",name:"Amit Rahul Kumar",role:"Bowler",speciality:"Swing"},
{id:"RW8",name:"Rohit Aakash Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"RW9",name:"Sandeep Manoj Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"RW10",name:"Vikas Deepak Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"RW11",name:"Nitin Kunal Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"RW12",name:"Rahul Pankaj Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"RW13",name:"Aakash Sachin Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"RW14",name:"Manoj Harshit Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"RW15",name:"Deepak Ankit Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Satna":[
{id:"ST1",name:"Naveen Sandeep Kumar",role:"Batsman",speciality:"Opener"},
{id:"ST2",name:"Dilip Vikas Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"ST3",name:"Ashutosh Nitin Kumar",role:"Bowler",speciality:"Fast"},
{id:"ST4",name:"Amit Rahul Kumar",role:"Batsman",speciality:"Anchor"},
{id:"ST5",name:"Rohit Aakash Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"ST6",name:"Sandeep Manoj Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"ST7",name:"Vikas Deepak Kumar",role:"Bowler",speciality:"Swing"},
{id:"ST8",name:"Nitin Kunal Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"ST9",name:"Rahul Pankaj Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"ST10",name:"Aakash Sachin Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"ST11",name:"Manoj Harshit Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"ST12",name:"Deepak Ankit Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"ST13",name:"Kunal Sunil Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"ST14",name:"Pankaj Rakesh Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"ST15",name:"Sachin Abhishek Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Sehore":[
{id:"SH1",name:"Amit Rahul Kumar",role:"Batsman",speciality:"Opener"},
{id:"SH2",name:"Rohit Aakash Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"SH3",name:"Sandeep Manoj Kumar",role:"Bowler",speciality:"Fast"},
{id:"SH4",name:"Vikas Deepak Kumar",role:"Batsman",speciality:"Anchor"},
{id:"SH5",name:"Nitin Kunal Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"SH6",name:"Rahul Pankaj Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"SH7",name:"Aakash Sachin Kumar",role:"Bowler",speciality:"Swing"},
{id:"SH8",name:"Manoj Harshit Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"SH9",name:"Deepak Ankit Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"SH10",name:"Kunal Sunil Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"SH11",name:"Pankaj Rakesh Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"SH12",name:"Sachin Abhishek Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"SH13",name:"Harshit Nilesh Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"SH14",name:"Ankit Saurabh Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"SH15",name:"Sunil Dinesh Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Shahdol":[
{id:"SD1",name:"Vikas Deepak Kumar",role:"Batsman",speciality:"Opener"},
{id:"SD2",name:"Nitin Kunal Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"SD3",name:"Rahul Pankaj Kumar",role:"Bowler",speciality:"Fast"},
{id:"SD4",name:"Aakash Sachin Kumar",role:"Batsman",speciality:"Anchor"},
{id:"SD5",name:"Manoj Harshit Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"SD6",name:"Deepak Ankit Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"SD7",name:"Kunal Sunil Kumar",role:"Bowler",speciality:"Swing"},
{id:"SD8",name:"Pankaj Rakesh Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"SD9",name:"Sachin Abhishek Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"SD10",name:"Harshit Nilesh Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"SD11",name:"Ankit Saurabh Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"SD12",name:"Sunil Dinesh Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"SD13",name:"Rakesh Manish Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"SD14",name:"Abhishek Piyush Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"SD15",name:"Nilesh Alok Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Shivpuri":[
{id:"SP1",name:"Aakash Sachin Kumar",role:"Batsman",speciality:"Opener"},
{id:"SP2",name:"Manoj Harshit Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"SP3",name:"Deepak Ankit Kumar",role:"Bowler",speciality:"Fast"},
{id:"SP4",name:"Kunal Sunil Kumar",role:"Batsman",speciality:"Anchor"},
{id:"SP5",name:"Pankaj Rakesh Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"SP6",name:"Sachin Abhishek Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"SP7",name:"Harshit Nilesh Kumar",role:"Bowler",speciality:"Swing"},
{id:"SP8",name:"Ankit Saurabh Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"SP9",name:"Sunil Dinesh Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"SP10",name:"Rakesh Manish Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"SP11",name:"Abhishek Piyush Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"SP12",name:"Nilesh Alok Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"SP13",name:"Saurabh Kapil Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"SP14",name:"Dinesh Yogesh Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"SP15",name:"Manish Pradeep Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Sidhi":[
{id:"SI1",name:"Kunal Sunil Kumar",role:"Batsman",speciality:"Opener"},
{id:"SI2",name:"Pankaj Rakesh Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"SI3",name:"Sachin Abhishek Kumar",role:"Bowler",speciality:"Fast"},
{id:"SI4",name:"Harshit Nilesh Kumar",role:"Batsman",speciality:"Anchor"},
{id:"SI5",name:"Ankit Saurabh Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"SI6",name:"Sunil Dinesh Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"SI7",name:"Rakesh Manish Kumar",role:"Bowler",speciality:"Swing"},
{id:"SI8",name:"Abhishek Piyush Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"SI9",name:"Nilesh Alok Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"SI10",name:"Saurabh Kapil Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"SI11",name:"Dinesh Yogesh Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"SI12",name:"Manish Pradeep Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"SI13",name:"Piyush Anuj Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"SI14",name:"Alok Aman Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"SI15",name:"Kapil Vivek Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Tikamgarh":[
{id:"TK1",name:"Harshit Nilesh Kumar",role:"Batsman",speciality:"Opener"},
{id:"TK2",name:"Ankit Saurabh Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"TK3",name:"Sunil Dinesh Kumar",role:"Bowler",speciality:"Fast"},
{id:"TK4",name:"Rakesh Manish Kumar",role:"Batsman",speciality:"Anchor"},
{id:"TK5",name:"Abhishek Piyush Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"TK6",name:"Nilesh Alok Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"TK7",name:"Saurabh Kapil Kumar",role:"Bowler",speciality:"Swing"},
{id:"TK8",name:"Dinesh Yogesh Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"TK9",name:"Manish Pradeep Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"TK10",name:"Piyush Anuj Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"TK11",name:"Alok Aman Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"TK12",name:"Kapil Vivek Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"TK13",name:"Yogesh Shubham Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"TK14",name:"Pradeep Kartik Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"TK15",name:"Anuj Ravi Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
],

"Ujjain":[
{id:"UJ1",name:"Rakesh Manish Kumar",role:"Batsman",speciality:"Opener"},
{id:"UJ2",name:"Abhishek Piyush Kumar",role:"All-Rounder",speciality:"Power Hitter"},
{id:"UJ3",name:"Nilesh Alok Kumar",role:"Bowler",speciality:"Fast"},
{id:"UJ4",name:"Saurabh Kapil Kumar",role:"Batsman",speciality:"Anchor"},
{id:"UJ5",name:"Dinesh Yogesh Kumar",role:"Bowler",speciality:"Death Overs"},
{id:"UJ6",name:"Manish Pradeep Kumar",role:"All-Rounder",speciality:"Finisher"},
{id:"UJ7",name:"Piyush Anuj Kumar",role:"Bowler",speciality:"Swing"},
{id:"UJ8",name:"Alok Aman Kumar",role:"Batsman",speciality:"Middle Order"},
{id:"UJ9",name:"Kapil Vivek Kumar",role:"Bowler",speciality:"Off Spin"},
{id:"UJ10",name:"Yogesh Shubham Kumar",role:"All-Rounder",speciality:"Utility"},
{id:"UJ11",name:"Pradeep Kartik Kumar",role:"Batsman",speciality:"Aggressive"},
{id:"UJ12",name:"Anuj Ravi Kumar",role:"Bowler",speciality:"Leg Spin"},
{id:"UJ13",name:"Aman Mukesh Kumar",role:"Batsman",speciality:"Stroke Player"},
{id:"UJ14",name:"Vivek Anurag Kumar",role:"All-Rounder",speciality:"Medium Pace"},
{id:"UJ15",name:"Shubham Pawan Kumar",role:"Wicket Keeper",speciality:"Safe Hands"}
]
};
